#!/usr/bin/env python3
"""
Henty Remote Setup Helper
Assists with configuring the server for remote access
"""

import os
import secrets
import socket
import sys
from pathlib import Path

class Colors:
    """ANSI color codes for terminal output"""
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.BOLD}{Colors.HEADER}{'='*80}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.HEADER}{text.center(80)}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.HEADER}{'='*80}{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}✅ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}⚠️  {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}❌ {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ️  {text}{Colors.END}")

def generate_api_key():
    """Generate a secure API key"""
    return secrets.token_urlsafe(32)

def get_local_ip():
    """Get local IP address"""
    try:
        # Create a socket to find the local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "Unable to determine"

def get_public_ip():
    """Get public IP address"""
    try:
        import requests
        response = requests.get('https://ifconfig.me', timeout=5)
        if response.status_code == 200:
            return response.text.strip()
    except Exception:
        pass
    return "Unable to determine"

def create_env_file(api_key):
    """Create or update .env file"""
    env_path = Path('.env')

    # Read existing .env if it exists
    existing_config = {}
    if env_path.exists():
        print_warning(".env file already exists. Creating backup...")
        backup_path = Path('.env.backup')
        with open(env_path, 'r') as f:
            content = f.read()
        with open(backup_path, 'w') as f:
            f.write(content)
        print_success(f"Backup created: {backup_path}")

        # Parse existing values
        for line in content.split('\n'):
            if '=' in line and not line.strip().startswith('#'):
                key, value = line.split('=', 1)
                existing_config[key.strip()] = value.strip()

    # Create new config
    config = {
        'SERVER_HOST': existing_config.get('SERVER_HOST', '0.0.0.0'),
        'SERVER_PORT': existing_config.get('SERVER_PORT', '5000'),
        'SERVER_DEBUG': existing_config.get('SERVER_DEBUG', 'False'),
        'REQUIRE_AUTH': existing_config.get('REQUIRE_AUTH', 'True'),
        'API_KEY': api_key,
        'ALLOWED_ORIGINS': existing_config.get('ALLOWED_ORIGINS', '*'),
        'ENABLE_WEBSOCKET': existing_config.get('ENABLE_WEBSOCKET', 'True'),
        'MAX_UPLOAD_SIZE': existing_config.get('MAX_UPLOAD_SIZE', '104857600')
    }

    # Write .env file
    with open(env_path, 'w') as f:
        f.write("# Henty Server Configuration\n")
        f.write("# Generated by setup_remote.py\n\n")

        f.write("# Server Network Settings\n")
        f.write(f"SERVER_HOST={config['SERVER_HOST']}\n")
        f.write(f"SERVER_PORT={config['SERVER_PORT']}\n")
        f.write(f"SERVER_DEBUG={config['SERVER_DEBUG']}\n\n")

        f.write("# Authentication\n")
        f.write(f"REQUIRE_AUTH={config['REQUIRE_AUTH']}\n")
        f.write(f"API_KEY={config['API_KEY']}\n\n")

        f.write("# CORS - Allowed Origins\n")
        f.write(f"ALLOWED_ORIGINS={config['ALLOWED_ORIGINS']}\n\n")

        f.write("# WebSocket Support\n")
        f.write(f"ENABLE_WEBSOCKET={config['ENABLE_WEBSOCKET']}\n\n")

        f.write("# Max Upload Size (bytes)\n")
        f.write(f"MAX_UPLOAD_SIZE={config['MAX_UPLOAD_SIZE']}\n")

    print_success(f".env file created: {env_path.absolute()}")
    return config

def create_client_config(server_ip, port, api_key):
    """Create client configuration file"""
    client_config_path = Path('client_config.js')

    config_content = f'''/**
 * Henty Client Configuration
 * Generated by setup_remote.py
 */

const HentyConfig = {{
    // Server URL - Update this if your server IP changes
    SERVER_URL: 'http://{server_ip}:{port}',

    // API Key for authentication
    API_KEY: '{api_key}',

    // WebSocket URL (auto-generated from SERVER_URL)
    WEBSOCKET_URL: null,

    // Request timeout in milliseconds
    TIMEOUT: 300000,  // 5 minutes

    // Enable debug logging
    DEBUG: false,

    /**
     * Get the full API URL for an endpoint
     */
    getApiUrl(endpoint) {{
        const cleanEndpoint = endpoint.startsWith('/') ? endpoint.slice(1) : endpoint;
        return `${{this.SERVER_URL}}/${{cleanEndpoint}}`;
    }},

    /**
     * Get WebSocket URL
     */
    getWebSocketUrl() {{
        return this.WEBSOCKET_URL || this.SERVER_URL;
    }},

    /**
     * Get headers for authenticated requests
     */
    getAuthHeaders() {{
        const headers = {{
            'Content-Type': 'application/json'
        }};
        if (this.API_KEY) {{
            headers['X-API-Key'] = this.API_KEY;
        }}
        return headers;
    }},

    /**
     * Make an authenticated fetch request
     */
    async fetch(endpoint, options = {{}}) {{
        const url = this.getApiUrl(endpoint);
        const headers = {{
            ...this.getAuthHeaders(),
            ...(options.headers || {{}})
        }};

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), this.TIMEOUT);

        try {{
            const response = await fetch(url, {{
                ...options,
                headers,
                signal: controller.signal
            }});

            clearTimeout(timeoutId);

            if (this.DEBUG) {{
                console.log(`[HentyConfig] ${{options.method || 'GET'}} ${{endpoint}}:`, response.status);
            }}

            return response;
        }} catch (error) {{
            clearTimeout(timeoutId);
            if (error.name === 'AbortError') {{
                throw new Error(`Request timeout after ${{this.TIMEOUT}}ms`);
            }}
            throw error;
        }}
    }},

    /**
     * Test connection to server
     */
    async testConnection() {{
        try {{
            const response = await this.fetch('/api/status');
            if (!response.ok) {{
                throw new Error(`Server returned ${{response.status}}`);
            }}
            const data = await response.json();
            console.log('✅ Successfully connected to server:', data);
            return data;
        }} catch (error) {{
            console.error('❌ Failed to connect to server:', error);
            throw error;
        }}
    }},

    /**
     * Get server configuration
     */
    async getServerConfig() {{
        try {{
            const response = await this.fetch('/api/config');
            if (!response.ok) {{
                throw new Error(`Failed to get config: ${{response.status}}`);
            }}
            return await response.json();
        }} catch (error) {{
            console.error('Failed to get server config:', error);
            return {{}};
        }}
    }}
}};

// Make available globally
window.HentyConfig = HentyConfig;

console.log('Henty Client Configuration loaded:', {{
    serverUrl: HentyConfig.SERVER_URL,
    hasApiKey: !!HentyConfig.API_KEY
}});
'''

    with open(client_config_path, 'w') as f:
        f.write(config_content)

    print_success(f"Client config created: {client_config_path.absolute()}")
    return client_config_path

def check_dependencies():
    """Check if required dependencies are installed"""
    print_info("Checking dependencies...")

    required_packages = [
        'flask',
        'flask_cors',
        'flask_socketio',
        'dotenv'
    ]

    missing = []
    for package in required_packages:
        try:
            __import__(package)
            print_success(f"{package} is installed")
        except ImportError:
            missing.append(package)
            print_error(f"{package} is NOT installed")

    if missing:
        print_warning(f"\nMissing packages: {', '.join(missing)}")
        print_info("Install with: pip install -r requirements.txt")
        return False

    print_success("All required dependencies are installed!\n")
    return True

def print_firewall_instructions():
    """Print firewall configuration instructions"""
    print_header("Firewall Configuration")

    print("To allow remote connections, you need to open port 5000 on your firewall:\n")

    print(f"{Colors.BOLD}Linux (ufw):{Colors.END}")
    print("  sudo ufw allow 5000/tcp\n")

    print(f"{Colors.BOLD}Linux (iptables):{Colors.END}")
    print("  sudo iptables -A INPUT -p tcp --dport 5000 -j ACCEPT\n")

    print(f"{Colors.BOLD}Windows PowerShell (Run as Administrator):{Colors.END}")
    print('  New-NetFirewallRule -DisplayName "Henty Server" -Direction Inbound -Protocol TCP -LocalPort 5000 -Action Allow\n')

    print(f"{Colors.BOLD}macOS:{Colors.END}")
    print("  System Preferences > Security & Privacy > Firewall > Firewall Options\n")

def main():
    """Main setup function"""
    print_header("Henty Remote Access Setup")

    print("This script will help you configure Henty for remote access.\n")

    # Check dependencies
    if not check_dependencies():
        response = input("\nInstall missing dependencies now? (y/n): ")
        if response.lower() == 'y':
            os.system("pip install -r requirements.txt")
            print("\nPlease run this script again after installation.\n")
        return

    # Generate API key
    print_header("API Key Generation")
    api_key = generate_api_key()
    print_success(f"Generated secure API key: {Colors.BOLD}{api_key}{Colors.END}\n")

    # Get network information
    print_header("Network Information")
    local_ip = get_local_ip()
    print_info(f"Local IP Address: {Colors.BOLD}{local_ip}{Colors.END}")

    print("\nFetching public IP address...")
    public_ip = get_public_ip()
    print_info(f"Public IP Address: {Colors.BOLD}{public_ip}{Colors.END}\n")

    # Create .env file
    print_header("Server Configuration")
    config = create_env_file(api_key)
    print()

    # Create client config
    print_header("Client Configuration")
    print("Choose which IP address to use for client configuration:\n")
    print(f"  1. Local Network (LAN): {local_ip}")
    print(f"  2. Public Internet (WAN): {public_ip}")
    print(f"  3. Custom IP address\n")

    choice = input("Enter choice (1/2/3) [1]: ").strip() or "1"

    if choice == "1":
        server_ip = local_ip
    elif choice == "2":
        server_ip = public_ip
        print_warning("Remember to configure port forwarding on your router!")
    else:
        server_ip = input("Enter custom IP address: ").strip()

    client_config_path = create_client_config(server_ip, config['SERVER_PORT'], api_key)
    print()

    # Firewall instructions
    print_firewall_instructions()

    # Final instructions
    print_header("Setup Complete!")

    print(f"{Colors.GREEN}Server Configuration:{Colors.END}")
    print(f"  • Configuration saved to: .env")
    print(f"  • API Key: {Colors.BOLD}{api_key}{Colors.END}")
    print(f"  • Server will listen on: {config['SERVER_HOST']}:{config['SERVER_PORT']}")
    print()

    print(f"{Colors.GREEN}Client Configuration:{Colors.END}")
    print(f"  • Configuration saved to: {client_config_path}")
    print(f"  • Server URL: http://{server_ip}:{config['SERVER_PORT']}")
    print()

    print(f"{Colors.YELLOW}Next Steps:{Colors.END}")
    print(f"  1. Configure your firewall (see instructions above)")
    print(f"  2. Start the server: {Colors.BOLD}python server.py{Colors.END}")
    print(f"  3. Share {Colors.BOLD}client_config.js{Colors.END} and {Colors.BOLD}index.html{Colors.END} with your collaborator")
    print(f"  4. Share the API key securely with your collaborator")
    print()

    print(f"{Colors.BLUE}Security Reminder:{Colors.END}")
    print(f"  • Keep your API key secret")
    print(f"  • Don't share it publicly or commit it to version control")
    print(f"  • Change it regularly for better security")
    print(f"  • Consider using HTTPS for internet access (see REMOTE_SETUP.md)")
    print()

    print(f"{Colors.GREEN}For detailed setup instructions, see: REMOTE_SETUP.md{Colors.END}\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Setup cancelled by user.{Colors.END}\n")
        sys.exit(0)
    except Exception as e:
        print_error(f"Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
